# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('date_scrapped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_string', models.URLField(max_length=350)),
                ('http_response_status', models.CharField(max_length=50)),
                ('is_live', models.BooleanField(default=True)),
                ('file_attached', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_url', to='url_scrapper.UploadedFile')),
            ],
        ),
    ]
