# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/pdf')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_file', to='url_scrapper.UploadedFile')),
            ],
        ),
    ]
